name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading Files
        run: |
          Invoke-WebRequest https://github.com/Tailscale/tailscale/releases/latest/download/tailscale-setup.exe -OutFile tailscale-setup.exe
          Start-Process tailscale-setup.exe -ArgumentList '/quiet' -Wait

      - name: Connect to Tailscale
        run: |
          tailscale up --authkey YOUR_TAILSCALE_AUTHKEY --hostname github-rdp

      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Display Connection Info
        run: |
          echo "✅ RDP is ready! Connect through Tailscale using the name: github-rdp"
          ipconfig
